"""
Tests for Stellar StrKey validation (backend/strkey.py).

Covers:
- Valid G-addresses (ed25519 public keys)
- Valid C-contract IDs
- Wrong types (G where C expected, C where G expected)
- Invalid checksums
- Malformed values (wrong length, invalid chars, non-string types)
- Nullable field handling
"""
from __future__ import annotations

import unittest

from strkey import (
    is_valid_strkey,
    validate_source_address,
    validate_contract_id,
    make_strkey,
    _VERSION_BYTE_ED25519_PUBLIC,
    _VERSION_BYTE_CONTRACT,
    _decode_base32,
    _crc16_xmodem,
)

# ---------------------------------------------------------------------------
# Well-known valid Stellar test addresses
# (generated by strkey.make_strkey with fixed payloads for determinism)
# ---------------------------------------------------------------------------

VALID_G_ADDRESS = "GCCHDCX2JTLB6FDKHGIAAQPS6JHBDETFXTCQRETJUP5BWBVT6G4LQKOQ"
VALID_C_CONTRACT = "CBQQWKW6JE6NAFM7HT7R5DNMCPISCVY275LPSUPIRLYTY3ICKYJDIANZ"


# ---------------------------------------------------------------------------
# is_valid_strkey tests
# ---------------------------------------------------------------------------

class IsValidStrkeyTest(unittest.TestCase):
    """Unit tests for is_valid_strkey()."""

    # --- Valid addresses -------------------------------------------------

    def test_valid_g_address_passes(self) -> None:
        self.assertTrue(
            is_valid_strkey(VALID_G_ADDRESS, _VERSION_BYTE_ED25519_PUBLIC)
        )

    def test_valid_c_contract_passes(self) -> None:
        self.assertTrue(
            is_valid_strkey(VALID_C_CONTRACT, _VERSION_BYTE_CONTRACT)
        )

    def test_lowercase_valid_address_accepted(self) -> None:
        lower = VALID_G_ADDRESS.lower()
        self.assertTrue(
            is_valid_strkey(lower, _VERSION_BYTE_ED25519_PUBLIC)
        )

    # --- Wrong type prefix ------------------------------------------------

    def test_g_address_rejected_as_contract(self) -> None:
        """A valid G-address must fail when validated as a C-contract."""
        self.assertFalse(
            is_valid_strkey(VALID_G_ADDRESS, _VERSION_BYTE_CONTRACT)
        )

    def test_c_contract_rejected_as_address(self) -> None:
        """A valid C-contract must fail when validated as a G-address."""
        self.assertFalse(
            is_valid_strkey(VALID_C_CONTRACT, _VERSION_BYTE_ED25519_PUBLIC)
        )

    # --- Invalid checksum ------------------------------------------------

    def test_tampered_checksum_rejected(self) -> None:
        """Changing a payload byte invalidates the CRC16 checksum."""
        # Change character at position 10 (in the payload, not the checksum area)
        tampered = VALID_G_ADDRESS[:10] + (
            "B" if VALID_G_ADDRESS[10] != "B" else "C"
        ) + VALID_G_ADDRESS[11:]
        self.assertFalse(
            is_valid_strkey(tampered, _VERSION_BYTE_ED25519_PUBLIC)
        )

    def test_tampered_checksum_c_contract_rejected(self) -> None:
        tampered = VALID_C_CONTRACT[:10] + (
            "B" if VALID_C_CONTRACT[10] != "B" else "C"
        ) + VALID_C_CONTRACT[11:]
        self.assertFalse(
            is_valid_strkey(tampered, _VERSION_BYTE_CONTRACT)
        )

    # --- Wrong length -----------------------------------------------------

    def test_too_short_rejected(self) -> None:
        self.assertFalse(
            is_valid_strkey("G" * 55, _VERSION_BYTE_ED25519_PUBLIC)
        )

    def test_too_long_rejected(self) -> None:
        self.assertFalse(
            is_valid_strkey("G" * 57, _VERSION_BYTE_ED25519_PUBLIC)
        )

    def test_empty_string_rejected(self) -> None:
        self.assertFalse(
            is_valid_strkey("", _VERSION_BYTE_ED25519_PUBLIC)
        )

    # --- Invalid characters -----------------------------------------------

    def test_invalid_base32_characters_rejected(self) -> None:
        # '0' and '1' are NOT in the Stellar base32 alphabet (A-Z2-7)
        bad = "G" * 55 + "0"
        self.assertFalse(
            is_valid_strkey(bad, _VERSION_BYTE_ED25519_PUBLIC)
        )

    # --- Non-string input -------------------------------------------------

    def test_none_rejected(self) -> None:
        self.assertFalse(is_valid_strkey(None, _VERSION_BYTE_ED25519_PUBLIC))

    def test_int_rejected(self) -> None:
        self.assertFalse(is_valid_strkey(12345, _VERSION_BYTE_ED25519_PUBLIC))


# ---------------------------------------------------------------------------
# validate_source_address tests
# ---------------------------------------------------------------------------

class ValidateSourceAddressTest(unittest.TestCase):
    """Tests for validate_source_address()."""

    def test_valid_g_address_returns_normalized(self) -> None:
        result = validate_source_address(VALID_G_ADDRESS)
        self.assertEqual(result, VALID_G_ADDRESS)

    def test_lowercase_g_address_normalized_to_uppercase(self) -> None:
        result = validate_source_address(VALID_G_ADDRESS.lower())
        self.assertEqual(result, VALID_G_ADDRESS)

    def test_whitespace_trimmed(self) -> None:
        result = validate_source_address(f"  {VALID_G_ADDRESS}  ")
        self.assertEqual(result, VALID_G_ADDRESS)

    def test_none_returns_none(self) -> None:
        result = validate_source_address(None)
        self.assertIsNone(result)

    def test_c_contract_rejected_for_g_address(self) -> None:
        with self.assertRaises(ValueError) as ctx:
            validate_source_address(VALID_C_CONTRACT)
        self.assertIn("sourceAddress", str(ctx.exception))
        self.assertIn("G-address", str(ctx.exception))

    def test_malformed_string_rejected(self) -> None:
        with self.assertRaises(ValueError) as ctx:
            validate_source_address("not-a-stellar-key-at-all")
        self.assertIn("sourceAddress", str(ctx.exception))
        self.assertIn("G-address", str(ctx.exception))

    def test_non_string_type_rejected(self) -> None:
        with self.assertRaises(ValueError) as ctx:
            validate_source_address(42)
        self.assertIn("sourceAddress", str(ctx.exception))
        self.assertIn("G-address", str(ctx.exception))

    def test_empty_string_rejected(self) -> None:
        with self.assertRaises(ValueError):
            validate_source_address("")

    def test_wrong_length_string_rejected(self) -> None:
        with self.assertRaises(ValueError):
            validate_source_address("G" * 10)


# ---------------------------------------------------------------------------
# validate_contract_id tests
# ---------------------------------------------------------------------------

class ValidateContractIdTest(unittest.TestCase):
    """Tests for validate_contract_id()."""

    def test_valid_c_contract_returns_normalized(self) -> None:
        result = validate_contract_id(VALID_C_CONTRACT)
        self.assertEqual(result, VALID_C_CONTRACT)

    def test_lowercase_c_contract_normalized_to_uppercase(self) -> None:
        result = validate_contract_id(VALID_C_CONTRACT.lower())
        self.assertEqual(result, VALID_C_CONTRACT)

    def test_whitespace_trimmed(self) -> None:
        result = validate_contract_id(f"  {VALID_C_CONTRACT}  ")
        self.assertEqual(result, VALID_C_CONTRACT)

    def test_none_returns_none(self) -> None:
        result = validate_contract_id(None)
        self.assertIsNone(result)

    def test_g_address_rejected_for_c_contract(self) -> None:
        with self.assertRaises(ValueError) as ctx:
            validate_contract_id(VALID_G_ADDRESS)
        self.assertIn("contractId", str(ctx.exception))
        self.assertIn("C-contract ID", str(ctx.exception))

    def test_malformed_string_rejected(self) -> None:
        with self.assertRaises(ValueError) as ctx:
            validate_contract_id("not-a-valid-contract")
        self.assertIn("contractId", str(ctx.exception))
        self.assertIn("C-contract ID", str(ctx.exception))

    def test_non_string_type_rejected(self) -> None:
        with self.assertRaises(ValueError) as ctx:
            validate_contract_id(42)
        self.assertIn("contractId", str(ctx.exception))
        self.assertIn("C-contract ID", str(ctx.exception))

    def test_empty_string_rejected(self) -> None:
        with self.assertRaises(ValueError):
            validate_contract_id("")

    def test_wrong_length_string_rejected(self) -> None:
        with self.assertRaises(ValueError):
            validate_contract_id("C" * 10)


# ---------------------------------------------------------------------------
# Base32 decode / CRC16 coupling tests
# ---------------------------------------------------------------------------

class StrKeyInternalsTest(unittest.TestCase):
    """Smoke-tests for the internal helpers to catch regressions."""

    def test_decode_base32_valid_g_address(self) -> None:
        decoded = _decode_base32(VALID_G_ADDRESS)
        self.assertEqual(len(decoded), 35)
        self.assertEqual(decoded[0], _VERSION_BYTE_ED25519_PUBLIC)

    def test_decode_base32_valid_c_contract(self) -> None:
        decoded = _decode_base32(VALID_C_CONTRACT)
        self.assertEqual(len(decoded), 35)
        self.assertEqual(decoded[0], _VERSION_BYTE_CONTRACT)

    def test_crc16_deterministic(self) -> None:
        data = b"hello"
        crc1 = _crc16_xmodem(data)
        crc2 = _crc16_xmodem(data)
        self.assertEqual(crc1, crc2)

    def test_crc16_different_for_different_data(self) -> None:
        crc1 = _crc16_xmodem(b"hello")
        crc2 = _crc16_xmodem(b"world")
        self.assertNotEqual(crc1, crc2)

    def test_make_strkey_roundtrip(self) -> None:
        """Encoding a version byte + payload must decode back to a valid StrKey."""
        import os
        payload = os.urandom(32)
        encoded = make_strkey(_VERSION_BYTE_ED25519_PUBLIC, payload)
        self.assertEqual(len(encoded), 56)
        self.assertTrue(is_valid_strkey(encoded, _VERSION_BYTE_ED25519_PUBLIC))


if __name__ == "__main__":
    unittest.main()
