/// Revocation witness integration (#98)
///
/// The registry supports a privacy-preserving credential revocation model
/// through the `RevocationWitness` Noir circuit (zk/noir/revocation_witness/).
///
/// ## Model
///
/// Revocation is represented as a Merkle tree of revoked credential roots:
///
///   - Each leaf is `pedersen_hash([credential_secret])` — the same
///     `credential_root` derivation used by the Silent Witness circuit.
///   - The circuit proves that a specific `credential_root` is a leaf in a
///     published Merkle tree WITHOUT revealing which leaf.
///   - A revocation-specific nullifier `pedersen_hash([credential_secret,
///     nullifier_secret])` prevents double-spending of revocation proofs.
///
/// ## Contract integration
///
/// The registry exposes a `revocation_root` concept via `RevocationRootRecord`.
/// An admin publishes the current Merkle root of revoked credentials.  The
/// circuit-based verification happens off-chain or through the external
/// verifier pattern; the contract stores and exposes the revocation root for
/// clients to reference.
///
/// ## Data flow
///
///   1. Admin calls `set_revocation_root(root)` to publish the current
///      revocation tree root.
///   2. A verifier (off-chain or external contract) accepts a Noir proof
///      generated by the `revocation_witness` circuit.
///   3. The proof demonstrates that a given credential_root belongs to the
///      currently-published revocation set without revealing the credential.
///
/// ## Future work
///
/// - On-chain Merkle proof verification through a dedicated Soroban verifier
///   contract for the revocation_witness circuit.
/// - Periodic revocation root rotation with historical root archival.
/// - Integration with `get_proof_status` to incorporate revocation-set
///   membership alongside per-proof revocation.
#[cfg(test)]
use super::*;
#[cfg(test)]
use soroban_sdk::{testutils::Address as _, testutils::Events as _, Address, Env};

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

#[cfg(test)]
fn b32(env: &Env, v: u8) -> BytesN<32> {
    BytesN::from_array(env, &[v; 32])
}

// ---------------------------------------------------------------------------
// Tests for the revocation-root management entry points
// ---------------------------------------------------------------------------

/// Admin can set and read back a revocation root.
#[test]
fn test_set_and_get_revocation_root() {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register(HarpocratesRegistry, ());
    let client = HarpocratesRegistryClient::new(&env, &contract_id);
    let admin = Address::generate(&env);
    client.init(&admin);

    let root = b32(&env, 0xAB);
    client.set_revocation_root(&admin, &root);

    let stored = client.get_revocation_root();
    assert_eq!(stored, Some(root));
}

/// Only admin can set the revocation root.
#[test]
#[should_panic(expected = "Error(Contract, #3)")]
fn test_non_admin_cannot_set_revocation_root() {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register(HarpocratesRegistry, ());
    let client = HarpocratesRegistryClient::new(&env, &contract_id);
    let admin = Address::generate(&env);
    let other = Address::generate(&env);
    client.init(&admin);

    client.set_revocation_root(&other, &b32(&env, 0xCD));
}

/// get_revocation_root returns None before any root is set.
#[test]
fn test_revocation_root_defaults_to_none() {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register(HarpocratesRegistry, ());
    let client = HarpocratesRegistryClient::new(&env, &contract_id);
    let admin = Address::generate(&env);
    client.init(&admin);

    assert_eq!(client.get_revocation_root(), None);
}

/// Revocation root can be updated (rotated) by the admin.
#[test]
fn test_revocation_root_can_be_rotated() {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register(HarpocratesRegistry, ());
    let client = HarpocratesRegistryClient::new(&env, &contract_id);
    let admin = Address::generate(&env);
    client.init(&admin);

    let root1 = b32(&env, 0x11);
    let root2 = b32(&env, 0x22);

    client.set_revocation_root(&admin, &root1);
    assert_eq!(client.get_revocation_root(), Some(root1));

    client.set_revocation_root(&admin, &root2);
    assert_eq!(client.get_revocation_root(), Some(root2));
}

/// Setting the revocation root emits an event.
#[test]
fn test_revocation_root_emits_event() {
    let env = Env::default();
    env.mock_all_auths();

    let contract_id = env.register(HarpocratesRegistry, ());
    let client = HarpocratesRegistryClient::new(&env, &contract_id);
    let admin = Address::generate(&env);
    client.init(&admin);

    client.set_revocation_root(&admin, &b32(&env, 0xAB));

    assert_ne!(
        env.events().all(),
        [].as_slice(),
        "expected at least one event after setting revocation root"
    );
}
